### ISSUE TITLE
Is super-jumbo appropriate?

### ISSUE THREAD

**Issue by tuexen** [emanjon/tls-super-jumbo-record-limit#1]
I'm wondering if using super-jumbo as an indication to increase the upper limit is too striking, since either super or jumbo would provide the information.
What about using "Large Record Sizes for (D)TLS"? Since the document will specify a flags extension to be used in combination with the record size limit extension to negotiate a record size limit larger than the currently protocol-defined record size limit, I don't think describing the contents as "an extension" or as an "flags extension" covers it. Maybe we should also not limit this in the title to 1.3, since it might also work in future versions of the protocol.

**Comment by emanjon** [comment]
>What about using "Large Record Sizes for (D)TLS"
>Maybe we should also not limit this in the title to 1.3
Sounds good to me. That is definitely a more appropriate name. TLS WG used to put 1.3 in titles, but I note the last RFC has title "Delegated Credentials for TLS and DTLS"

**Comment by emanjon** [comment]
The orignal draft was written for 1.2 and 1.3. With the flag extension this would be 1.3 only. I will remove all mention of 1.2

**Comment by emanjon** [comment]
Done in main
